server:
  port: 8081

spring:
  application:
    name: sms-service
  
  cloud:
    config:
      uri: http://localhost:8888
      username: configuser
      password: configpass
  
  datasource:
    url: jdbc:mysql://localhost:3306/sms_monitoring?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: smsuser
    password: smspassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Custom application properties
sms:
  platform:
    simulation:
      enabled: true
      default-success-rate: 0.90
      max-concurrent-messages: 1000
    monitoring:
      metrics-interval: 30
      alert-threshold: 0.80

logging:
  level:
    com.smsplatform: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/sms-service.log

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/sms_monitoring?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    config:
      uri: http://config-server:8888

